In [1]:
#Задача 1
import numpy as np
a = np.array([[1, 2, 1], [-2, 1, 1]])
b = np.array([[3, 1], [-1, 0], [2, 4]])
c = np.array([[-2, 2], [1, -1], [1, 2]])

In [9]:
b + 2 * c # выполнение операции В+2С

array([[ 1,  3],
       [ 0, -1],
       [ 3,  6]])

In [22]:
an = a.ravel() # так как размерность двух массивов не согласована, и не позволят проводить операции над ними
bn = b.ravel() # преобразуем оба массива в одномерный
an + 2 * bn # выполненеие операции А+2В

array([ 7,  4, -1, -2,  5,  9])

In [23]:
#Задача 2
Z = np.zeros((8,8), dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [29]:
#Задача 3
a = np.linspace(0, 1.4, 15, 0.1) #cоздаем первый вектор длиной 15 элементов, значения от 0 до 1.4, шаг 0.1
b = np.linspace(1, 6, 6)         #создаем второй вектор длиной 6 элементов, значения от 1 до 6
print(a)
print(b)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4]
[1. 2. 3. 4. 5. 6.]


In [28]:
a_m = np.array(a).reshape(5, 3)  #преобразуем первый вектор в матрицу 5х3
b_m = np.array(b).reshape(3, 2)  #преобразуем второй вектор в матрицу 3х2
print(a_m)
print(b_m)

[[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]
 [0.9 1.  1.1]
 [1.2 1.3 1.4]]
[[1. 2.]
 [3. 4.]
 [5. 6.]]


In [34]:
np.matmul(a_m, b_m) #перемножаем матрицы

array([[ 1.3,  1.6],
       [ 4. ,  5.2],
       [ 6.7,  8.8],
       [ 9.4, 12.4],
       [12.1, 16. ]])

In [48]:
#Задача 4
a = np.arange(1, 36, 2, dtype=np.int32)  # создаем вектор целых чисел размерностью 32 , значениями 1,3,5,7... и т.д, тип элементов int32
print(a)
print(a[1::3])  #используем срез, чтобы выделить все элементы со значениями кратными 3

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35]
[ 3  9 15 21 27 33]
